-- CreateTable
CREATE TABLE "home_page_content" (
    "id" TEXT NOT NULL DEFAULT 'homepage',
    "heroBadge" TEXT NOT NULL DEFAULT 'ยินผัน ฟุตบอล อคาเดมี',
    "heroTitleLine1" TEXT NOT NULL DEFAULT 'สอนโดย',
    "heroTitleHighlight1" TEXT NOT NULL DEFAULT 'ทีมชาติ',
    "heroTitleLine2" TEXT NOT NULL DEFAULT 'ฟื้นฟูโดย',
    "heroTitleHighlight2" TEXT NOT NULL DEFAULT 'มืออาชีพ',
    "heroDescription" TEXT NOT NULL DEFAULT 'สถาบันฟุตบอลที่ดำเนินงานโดยคู่ครองผู้เชี่ยวชาญคนละด้าน ผสานการฝึกซ้อมจากอดีตนักเตะทีมชาติ เข้ากับการดูแลฟื้นฟูร่างกายจากนักกายภาพบำบัดมืออาชีพ ในสถาบันเดียว',
    "heroCtaPrimaryLabel" TEXT NOT NULL DEFAULT 'สมัครเรียนวันนี้',
    "heroCtaSecondaryLabel" TEXT NOT NULL DEFAULT 'รู้จักเรามากขึ้น',
    "heroChip1Title" TEXT NOT NULL DEFAULT 'โค้ช + นักกายภาพ',
    "heroChip1Desc" TEXT NOT NULL DEFAULT 'ทีมงานมืออาชีพในที่เดียว',
    "heroChip2Title" TEXT NOT NULL DEFAULT 'ฝึกซ้อม',
    "heroChip2Desc" TEXT NOT NULL DEFAULT 'ทุกช่วงวัย',
    "heroChip3Title" TEXT NOT NULL DEFAULT 'ฟื้นฟู',
    "heroChip3Desc" TEXT NOT NULL DEFAULT 'คลินิกกายภาพ',
    "uspSectionTitle" TEXT NOT NULL DEFAULT 'สองมืออาชีพ หนึ่งเป้าหมาย',
    "uspSectionSubtitle" TEXT NOT NULL DEFAULT 'ความเชี่ยวชาญที่แตกต่างกัน ผสานกันเพื่อพัฒนานักเรียนอย่างรอบด้าน',
    "usp1Tag" TEXT NOT NULL DEFAULT 'โค้ชหลัก',
    "usp1Title" TEXT NOT NULL DEFAULT 'สอนโดยอดีตนักเตะทีมชาติ',
    "usp1Name" TEXT NOT NULL DEFAULT 'ภานุวัฒน์ ยินผัน',
    "usp1Desc" TEXT NOT NULL DEFAULT 'อดีตนักฟุตบอลทีมชาติไทย ติดทีมดาราเอเชีย (Asian All-Star) หลายสมัย ถ่ายทอดเทคนิคและประสบการณ์ระดับนานาชาติสู่นักเรียนทุกรุ่น',
    "usp2Tag" TEXT NOT NULL DEFAULT 'หัวหน้าคลินิก',
    "usp2Title" TEXT NOT NULL DEFAULT 'ฟื้นฟูโดยมืออาชีพ',
    "usp2Name" TEXT NOT NULL DEFAULT 'ผู้ร่วมก่อตั้ง / นักกายภาพบำบัด',
    "usp2Desc" TEXT NOT NULL DEFAULT 'อดีตนักกายภาพบำบัดประจำทีมฟุตบอลหลายทีม ดูแลคลินิกกายภาพและฟื้นฟูของสถาบันโดยตรง ลดความเสี่ยงบาดเจ็บและเสริมสมรรถภาพนักกีฬา',
    "highlightsSectionTitle" TEXT NOT NULL DEFAULT 'ทำไมต้องยินผัน ฟุตบอล อคาเดมี',
    "highlight1Title" TEXT NOT NULL DEFAULT 'หลักสูตรตามช่วงวัย',
    "highlight1Desc" TEXT NOT NULL DEFAULT 'ออกแบบการฝึกให้เหมาะกับพัฒนาการของนักเรียนแต่ละรุ่น ตั้งแต่ระดับเริ่มต้นถึงระดับแข่งขัน',
    "highlight2Title" TEXT NOT NULL DEFAULT 'ดูแลครบวงจร',
    "highlight2Desc" TEXT NOT NULL DEFAULT 'ฝึกซ้อมฟุตบอลควบคู่การประเมินร่างกายและฟื้นฟูอาการบาดเจ็บ โดยทีมงานเฉพาะทาง',
    "highlight3Title" TEXT NOT NULL DEFAULT 'แจ้งเตือนผ่าน LINE',
    "highlight3Desc" TEXT NOT NULL DEFAULT 'ตารางฝึกซ้อม การนัดหมาย และผลการเข้าเรียน แจ้งเตือนถึงผู้ปกครองแบบเรียลไทม์',
    "programsSectionTitle" TEXT NOT NULL DEFAULT 'คอร์สเรียนตามช่วงวัย',
    "programsSectionSubtitle" TEXT NOT NULL DEFAULT 'ตัวอย่างการจัดกลุ่มรุ่น — รายละเอียดคอร์สฉบับเต็มเร็วๆ นี้',
    "program1Age" TEXT NOT NULL DEFAULT '6–9 ปี',
    "program1Name" TEXT NOT NULL DEFAULT 'เยาวชนเริ่มต้น',
    "program1Desc" TEXT NOT NULL DEFAULT 'ปูพื้นฐานทักษะบอลและความสนุกในการเล่น',
    "program2Age" TEXT NOT NULL DEFAULT '10–13 ปี',
    "program2Name" TEXT NOT NULL DEFAULT 'เยาวชนพัฒนา',
    "program2Desc" TEXT NOT NULL DEFAULT 'พัฒนาเทคนิคเฉพาะตำแหน่งและการอ่านเกม',
    "program3Age" TEXT NOT NULL DEFAULT '14–18 ปี',
    "program3Name" TEXT NOT NULL DEFAULT 'เยาวชนสู่ทีมชาติ',
    "program3Desc" TEXT NOT NULL DEFAULT 'ยกระดับสู่การแข่งขันและเตรียมความพร้อมสู่ทีมระดับสูง',
    "ctaTitle" TEXT NOT NULL DEFAULT 'พร้อมให้ลูกของคุณก้าวสู่สนามหญ้าแล้วหรือยัง?',
    "ctaDescription" TEXT NOT NULL DEFAULT 'สมัครเรียนวันนี้ พร้อมรับการดูแลจากทีมโค้ชและนักกายภาพบำบัดมืออาชีพ',
    "ctaButtonLabel" TEXT NOT NULL DEFAULT 'เริ่มต้นเลย',
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "home_page_content_pkey" PRIMARY KEY ("id")
);
