-- CreateTable
CREATE TABLE "about_page_content" (
    "id" TEXT NOT NULL DEFAULT 'about',
    "showHeroBadge" BOOLEAN NOT NULL DEFAULT true,
    "heroBadge" TEXT NOT NULL DEFAULT 'เกี่ยวกับเรา',
    "heroTitle" TEXT NOT NULL DEFAULT 'สองความเชี่ยวชาญ หนึ่งความตั้งใจ เพื่อนักเตะรุ่นใหม่',
    "heroDescription" TEXT NOT NULL DEFAULT 'ยินผัน ฟุตบอล อคาเดมี ก่อตั้งโดยคู่ครองที่เชี่ยวชาญคนละด้าน ฝั่งหนึ่งคืออดีตนักเตะทีมชาติผู้เข้าใจเกมลูกหนังอย่างลึกซึ้ง อีกฝั่งคือนักกายภาพบำบัดมืออาชีพผู้ดูแลร่างกายนักกีฬามาแล้วนับไม่ถ้วน เราเชื่อว่าการพัฒนานักฟุตบอลที่ดี ต้องดูแลทั้งฝีเท้าและร่างกายไปพร้อมกัน',
    "showFoundersSection" BOOLEAN NOT NULL DEFAULT true,
    "showFoundersSectionTitle" BOOLEAN NOT NULL DEFAULT true,
    "foundersSectionTitle" TEXT NOT NULL DEFAULT 'ผู้ก่อตั้งของเรา',
    "showFoundersSectionSubtitle" BOOLEAN NOT NULL DEFAULT true,
    "foundersSectionSubtitle" TEXT NOT NULL DEFAULT 'สองมืออาชีพ สองบทบาท ในสถาบันเดียว',
    "showFounder1" BOOLEAN NOT NULL DEFAULT true,
    "founder1Initials" TEXT NOT NULL DEFAULT 'ภย',
    "founder1Role" TEXT NOT NULL DEFAULT 'ผู้ก่อตั้ง / หัวหน้าโค้ช',
    "founder1Name" TEXT NOT NULL DEFAULT 'ภานุวัฒน์ ยินผัน',
    "founder1Bio" TEXT NOT NULL DEFAULT 'อดีตนักฟุตบอลทีมชาติไทย ติดทีมดาราเอเชีย (Asian All-Star) หลายสมัย ผันตัวมาถ่ายทอดความรู้และประสบการณ์การเล่นในระดับนานาชาติ เพื่อปั้นนักเตะเยาวชนรุ่นใหม่ให้เติบโตอย่างถูกวิธี ทั้งด้านเทคนิค ทัศนคติ และวินัยในสนาม',
    "founder1PhotoUrl" TEXT,
    "showFounder2" BOOLEAN NOT NULL DEFAULT true,
    "founder2Initials" TEXT NOT NULL DEFAULT 'PT',
    "founder2Role" TEXT NOT NULL DEFAULT 'ผู้ร่วมก่อตั้ง / หัวหน้านักกายภาพบำบัด',
    "founder2Name" TEXT NOT NULL DEFAULT 'ผู้ร่วมก่อตั้ง — นักกายภาพบำบัด',
    "founder2Bio" TEXT NOT NULL DEFAULT 'อดีตนักกายภาพบำบัดประจำทีมฟุตบอลหลายทีม สั่งสมประสบการณ์ดูแลนักกีฬาอาชีพ ปัจจุบันดูแลคลินิกกายภาพและฟื้นฟูของสถาบันโดยตรง เพื่อลดความเสี่ยงการบาดเจ็บและช่วยให้นักเรียนกลับมาเล่นได้อย่างปลอดภัย',
    "founder2PhotoUrl" TEXT,
    "showMissionSection" BOOLEAN NOT NULL DEFAULT true,
    "showMission1" BOOLEAN NOT NULL DEFAULT true,
    "mission1Title" TEXT NOT NULL DEFAULT 'พันธกิจของเรา',
    "mission1Desc" TEXT NOT NULL DEFAULT 'พัฒนานักฟุตบอลเยาวชนอย่างรอบด้าน ทั้งทักษะในสนามและสุขภาพร่างกาย ภายใต้การดูแลของผู้เชี่ยวชาญจริง',
    "showMission2" BOOLEAN NOT NULL DEFAULT true,
    "mission2Title" TEXT NOT NULL DEFAULT 'แนวทางการสอน',
    "mission2Desc" TEXT NOT NULL DEFAULT 'ผสานประสบการณ์จริงจากสนามแข่งขันระดับนานาชาติ เข้ากับหลักวิทยาศาสตร์การกีฬาและกายภาพบำบัด',
    "showMission3" BOOLEAN NOT NULL DEFAULT true,
    "mission3Title" TEXT NOT NULL DEFAULT 'ดูแลครบวงจร',
    "mission3Desc" TEXT NOT NULL DEFAULT 'ตั้งแต่การฝึกซ้อม การประเมินร่างกาย ไปจนถึงการฟื้นฟูอาการบาดเจ็บ ในสถาบันเดียว',
    "showCtaSection" BOOLEAN NOT NULL DEFAULT true,
    "showCtaTitle" BOOLEAN NOT NULL DEFAULT true,
    "ctaTitle" TEXT NOT NULL DEFAULT 'มาร่วมเป็นส่วนหนึ่งของยินผัน ฟุตบอล อคาเดมี',
    "ctaButtonLabel" TEXT NOT NULL DEFAULT 'สมัครเรียน',
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "about_page_content_pkey" PRIMARY KEY ("id")
);
